version: '3.4'

services:
  mongo:
    ports:
      - 27017:27017

  scraper:
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: 'mongo'
      SCRAPE_RICH_ATTRIBUTES: ${SCRAPE_RICH_ATTRIBUTES:-1}
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  runner:
    environment:
      SCRAPER_FREQUENCY_MINUTES: ${SCRAPER_FREQUENCY_MINUTES:-10}
      SOURCE: ${SOURCE}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_API_BASE_URL: ${MAILGUN_API_BASE_URL}
      MAILGUN_NOTIFY_EMAIL: ${MAILGUN_NOTIFY_EMAIL}
      NOTIFY: ${NOTIFY:-0}
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  test:
    image: scraper
    depends_on:
      - runner
      - scraper
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  queue:
    image: mixmaxhq/arena
    ports:
      - 4567:4567
    volumes:
      - ./scraper/index.json:/opt/arena/src/server/config/index.json

  frontend:
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
