version: '3.4'

services:
  api:
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  monitor:
    image: scraper
    ports:
      - 4567:4567
    command: 'npm run monitor'
    depends_on:
      - scraper
      - postgres
      - redis

  redis:
    ports:
      - 6379:6379

  test:
    image: scraper
    depends_on:
      - scraper
      - api
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  scraper:
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  manager:
    ports:
      - 3000:3000
    volumes:
      - ./manager:/usr/src/app
      - /usr/src/app/node_modules
