version: '3.4'

services:
  mongo:
    ports:
      - 27017:27017

  scraper:
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: 'mongo'
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  monitor:
    image: scraper
    ports:
      - 4567:4567
    command: 'npm run monitor'
    depends_on:
      - scraper
      - mongo
      - redis

  test:
    image: scraper
    depends_on:
      - runner
      - scraper
    volumes:
      - ./scraper:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
