version: '3.4'

services:
  mongo:
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017

  scraper:
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: 'mongo'
    volumes:
      - ./scraper:/usr/src/app

  runner:
    environment:
      SCRAPER_FREQUENCY: ${SCRAPER_FREQUENCY:-10}
    volumes:
      - ./scraper:/usr/src/app
  
  frontend:
    restart: always
    ports:
      - 8080:8080