version: '3.4'

services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  scraper:
    image: scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongo
    environment:
      MONGODB_URI: 'mongo'
    command: 'npm run serve'

  runner:
    image: scraper
    environment:
      MONGODB_URI: 'mongo'
    command: 'npm run start'
    depends_on:
      - scraper

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: 'npm run start'
    depends_on:
      - mongo

volumes:
  mongo: ~
