version: '3.4'

services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  scraper:
    restart: always
    image: scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      MONGODB_URI: 'mongo'
      REDIS_URL: 'redis://cache:6379'
      POSTGRES_URL: 'postgres'
    command: 'npm run serve'

  runner:
    image: scraper
    command: 'npm run start'
    environment:
      MONGODB_URI: 'mongo'
      REDIS_URL: 'redis://cache:6379'
    depends_on:
      - scraper

  checker:
    image: scraper
    environment:
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_API_BASE_URL: ${MAILGUN_API_BASE_URL}
      MAILGUN_NOTIFY_EMAIL: ${MAILGUN_NOTIFY_EMAIL}
      NOTIFY: ${NOTIFY:-0}
      REDIS_URL: 'redis://cache:6379'
      MONGODB_URI: 'mongo'
    command: 'npm run checker'
    depends_on:
      - scraper

  frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: 'npm run start'
    depends_on:
      - mongo

  redis:
      image: redis
      container_name: cache
      ports:
        - 6379:6379

volumes:
  mongo: ~
