version: '3.4'

services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  scraper:
    restart: always
    image: scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: 'mongo'
      REDIS_URL: 'redis://cache:6379'
    command: 'npm run serve'

  runner:
    image: scraper
    environment:
      MONGODB_URI: 'mongo'
    command: 'npm run start'
    depends_on:
      - scraper

  frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: 'npm run start'
    depends_on:
      - mongo

  redis:
      image: redis
      container_name: cache
      ports:
        - 6379:6379

volumes:
  mongo: ~
