version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  scraper:
    restart: always
    image: scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    command: 'npm start'
    environment:
      REDIS_URL: 'redis://cache:6379'
      POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres
      - redis

  api:
    restart: always
    build:
      context: .
      dockerfile: api/Dockerfile
    command: 'npm start'
    environment:
      POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres

  manager:
    restart: always
    build:
      context: .
      dockerfile: manager/Dockerfile
    command: 'npm start'
    depends_on:
      - api

  redis:
    image: redis
    container_name: cache

volumes:
  postgres: ~
