version: '3.4'

services:
  mongo:
    ports:
      - 27017:27017

  scraper:
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: 'mongo'
    volumes:
      - ./scraper:/usr/src/app

  runner:
    environment:
      SCRAPER_FREQUENCY_MINUTES: ${SCRAPER_FREQUENCY_MINUTES:-10}
    volumes:
      - ./scraper:/usr/src/app

  test:
    image: scraper
    depends_on:
    - runner
    - scraper
    volumes:
      - ./scraper:/usr/src/app

  frontend:
    ports:
      - 8080:8080
